### PR TITLE
Adds flowcontrol metaprogramming module

### PR DESCRIPTION
**Pull request by FRC2539**
This module can make command groups more readable when using conditional logic. For complete documentation, see [this pull request](https://github.com/robotpy/robotpy-docs/pull/9).

### CODE REVIEW

**Comment by virtuald** [comment]
Looks cool, can you add some simple tests to ensure that we don't accidentally break it in the future?

File: commandbased/flowcontrol.py [hunk 1]
```diff
@@ -0,0 +1,289 @@
...
+    The decorated function must accept one positional argument that will be used
+    as its 'self'.
+    '''
+
+    def flowcontrolIF(func):
+        parent = _getCommandGroup()
+        _hookCommandGroup(parent)
+
+        cg = _buildCommandGroup(func, parent)
+        parent._ifStack = [(condition, cg)]
```
Comment (virtuald) [inline commandbased/flowcontrol.py]: Shouldn't there be an error if the `_ifStack` already exists?

File: commandbased/flowcontrol.py [hunk 2]
```diff
@@ -0,0 +1,289 @@
...
+    CommandGroup which will be triggered by a ConditionalCommand that uses the
+    passed condition. That ConditionalCommand will then be added as the onFalse
+    for the ConditionalCommand created by a previous IF or ELIF.
+    '''
+
+    def flowcontrolELIF(func):
+        parent = _getCommandGroup()
+
+        cg = _buildCommandGroup(func, parent)
+        parent._ifStack.append((condition, cg))
```
Comment (virtuald) [inline commandbased/flowcontrol.py]: Probably should give a better error message if the `_ifStack` isn't defined

**Comment by FRC2539** [comment]
We tried to come up with tests, but executing `./run_tests.sh` generates a bunch of `AttributeError: type object 'NetworkTables' has no attribute 'startTestMode'` messages. We updated pynetworktables with pip, but that did not fix the problem.

Additionally, we don't know how to check if a command is run correctly by the Scheduler inside a test.

**Comment by virtuald** [comment]
Sorry about that, you need to install the git version of pynetworktables.

I would accept python-specific additions to robotpy-wpilib to make testing commands simpler to do.

**Comment by FRC2539** [comment]
The current version of ConditionalCommand has many issues. We have an [open pull request](https://github.com/wpilibsuite/allwpilib/pull/690) to fix this upstream, but we need to add the fixed version to the commandbased package for the moment in order for the tests to pass.

File: commandbased/flowcontrol.py [hunk 3]
```diff
@@ -19,7 +19,11 @@ def _getCommandGroup():
     '''
     # https://stackoverflow.com/a/14694234
     stack = inspect.stack()
-    frame = stack[2].frame
+    try:
+        frame = stack[2].frame
+    except AttributeError:
+        # Python < 3.5
+        frame = stack[2][0]
```
Comment (auscompgeek) [inline commandbased/flowcontrol.py]: `inspect.stack()` returns a list of named tuples, so `stack[2][0]` should also work on Python 3.5+. However, `inspect.currentframe().f_back.f_back` or even `sys._getframe(2)` should work as well. Best to avoid unnecessary work.

I wonder if there's a better way of doing all this though. Probably not.

Comment (FRC2539) [reply commandbased/flowcontrol.py]: Unfortunately, both `sys._getframe` and `inspect.currentframe` are implementation dependent. It's a shame to lose readability just to maintain compatibility with 2014, but it makes more sense than keeping a check just to point out that we're doing that.

**Comment by virtuald** [comment]
I've poked the wpilib developers to look at your PR, so I'm going to wait for that first. However, everything else here seems fine to me.

File: commandbased/flowcontrol.py [hunk 4]
```diff
@@ -0,0 +1,305 @@
...
+from commandbased.cancelcommand import CancelCommand
+
+import inspect
+
+__all__ = ['IF', 'ELIF', 'ELSE', 'WHILE', 'RETURN', 'BREAK']
+
+'''
+These functions can be used to make programming CommandGroups much more
+intuitive. For more information, check each method's docstring.
+'''
```
Comment (auscompgeek) [inline commandbased/flowcontrol.py]: This is meant to be a module docstring, right? This needs to be the first statement to be a docstring.

Also, this is just me being nitpicky, but [PEP 257](https://www.python.org/dev/peps/pep-0257/) says that docstrings conventionally use double quotes rather than single quotes.

File: commandbased/flowcontrol.py [hunk 5]
```diff
@@ -0,0 +1,305 @@
+from wpilib.command.command import Command
+from wpilib.command.commandgroup import CommandGroup
```
Comment (auscompgeek) [inline commandbased/flowcontrol.py]: I believe the preferred way of spelling this is `from wpilib.command import Command, CommandGroup`.

File: tests/test_flowcontrol.py [hunk 6]
```diff
@@ -0,0 +1,385 @@
+import pytest
+
+from wpilib.command import Scheduler
+from wpilib.command import InstantCommand
+from wpilib.command import CommandGroup
+import wpilib.command.command
```
Comment (auscompgeek) [inline tests/test_flowcontrol.py]: Unused import?

**Comment by FRC2539** [comment]
Is support for Python 3.4 being dropped? If so, we'd like to restore the `namedtuple` usage in the stack inspection logic.

**Comment by virtuald** [comment]
Nobody has told me that they want Python 3.4 support yet. I'll pose the question to https://github.com/robotpy/robotpy-wpilib/issues/355

**Comment by auscompgeek** [comment]
With the stack inspection stuff… all that stuff in `inspect` is implementation-optional anyway. All the Python 3 implementations that _don't_ implement `sys._getframe()` et al are those that don't run in the traditional Python environment (MicroPython, browsers, Java, …).

Both CPython and PyPy support `sys._getframe()`.

I wonder if there's a better way of doing what you're using it for than this though. Hmm.

**Comment by auscompgeek** [comment]
Good news @FRC2539 - we're dropping Python 3.4 support. Feel free to rebase once #75 is merged and put your namedtuple usage back in (or maybe just use `sys._getframe()` directly, who knows).

**Comment by virtuald** [comment]
@FRC2539 I suspect that your PR isn't going to get merged, so I'm fine with merging this as is. Let us know whether you want to merge this now, or if you want to revert your python 3.4 specific changes.

**Comment by FRC2539** [comment]
This has been updated and is ready to be merged

**Comment by twinters007** [comment]
Upstream still has the open PR, so I’m not sure we should merge if they haven’t made the corresponding changes

**Comment by FRC2539** [comment]
This change assumes that PR will not be merged this season, and includes a working version of `ConditionalCommand` that it uses instead of the one from upstream.
